version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t trythepsy:latest .
      - docker tag trythepsy:latest 128139028850.dkr.ecr.eu-west-1.amazonaws.com/trythepsy:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 128139028850.dkr.ecr.eu-west-1.amazonaws.com/trythepsy:latest