mutation updateArtist($id: ID!, $name: String!, $realname: String!, $bio: String!, $image: String!, $facebook: String, $twitter: String, $instagram: String, $deezer: String, $soundcloud: String, $youtube: String) {
  updateArtist(id: $id, name: $name, realname: $realname, bio: $bio, image: $image, facebook: $facebook, twitter: $twitter, instagram: $instagram, deezer: $deezer, soundcloud: $soundcloud, youtube: $youtube) {
    name
    realname
    bio
    image
    facebook
    twitter
    instagram
    deezer
    soundcloud
    youtube
  }
}